# Trustpilot Review Scraper – FirstPort

This notebook scrapes **all public reviews** for [firstport.co.uk on Trustpilot](https://www.trustpilot.com/review/www.firstport.co.uk)  
using the open‑source [`trustpilot_scraper`](https://github.com/irfanalidv/trustpilot_scraper) library and saves them to CSV.

> **Notes**  
> • Scraping respects Trustpilot’s rate‑limits (2 s delay/page).  
> • For anything beyond internal analysis, review Trustpilot’s current ToS.  
> • The code should run as‑is in any recent Jupyter environment (Python 3.8+).

# Setup

In [ ]:
# Install required packages
!pip install -U -q requests beautifulsoup4 pandas tqdm

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.9/89.9 kB 2.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.1/13.1 MB 99.1 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 2.2.3 which is incompatible.

In [ ]:
import requests
from bs4 import BeautifulSoup
import json
import time
import pandas as pd
from tqdm.notebook import tqdm  # Use tqdm.notebook for Jupyter compatibility
import re
import os
from datetime import datetime

def get_reviews_from_page(url):
    """Get reviews from a specific Trustpilot page URL"""
    try:
        headers = {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
            "Accept-Language": "en-US,en;q=0.5"
        }

        req = requests.get(url, headers=headers)
        req.raise_for_status()

        soup = BeautifulSoup(req.text, 'html.parser')

        # Try to find total review count for validation
        total_reviews_pattern = re.compile(r'showing \d+-\d+ of ([\d,]+) reviews', re.IGNORECASE)
        pagination_text = soup.find(string=total_reviews_pattern)
        if pagination_text:
            match = total_reviews_pattern.search(pagination_text)
            if match:
                total_count = match.group(1).replace(',', '')
                print(f"Site reports approximately {total_count} total reviews")

        reviews_raw = soup.find("script", id="__NEXT_DATA__")
        if not reviews_raw:
            print(f"WARNING: Could not find __NEXT_DATA__ script on page {url}")
            return []

        reviews_raw = json.loads(reviews_raw.string)

        # Check if we have the expected structure
        if not (reviews_raw.get("props") and
                reviews_raw["props"].get("pageProps") and
                reviews_raw["props"]["pageProps"].get("reviews")):
            print(f"WARNING: Unexpected data structure on page {url}")
            return []

        reviews = reviews_raw["props"]["pageProps"]["reviews"]

        # Add page info to each review for tracking
        page_num = int(url.split("page=")[-1]) if "page=" in url else 1
        for review in reviews:
            review['_page_number'] = page_num

        # Look for pagination info
        pagination = reviews_raw["props"]["pageProps"].get("pagination", {})
        if pagination:
            current = pagination.get("page", "?")
            total = pagination.get("totalPages", "?")
            print(f"Page {current}/{total}")

        return reviews
    except Exception as e:
        print(f"Error fetching page {url}: {e}")
        return []

def scrape_trustpilot_reviews(base_url, start_page=1, end_page=None, max_pages=None, verbose=True):
    """
    Scrape Trustpilot reviews with page range control

    Parameters:
    - base_url: The base URL of the Trustpilot page
    - start_page: Page number to start scraping from (default: 1)
    - end_page: Page number to end scraping at (inclusive, default: None = no limit)
    - max_pages: Maximum number of pages to scrape (default: None = no limit)
    - verbose: Whether to print detailed progress information

    Returns:
    - List of review dictionaries
    """
    reviews_data = []
    page_number = start_page
    total_reviews = 0
    retry_count = 0
    max_retries = 3
    empty_pages = 0
    max_empty_pages = 3  # Stop after this many consecutive empty pages
    pages_scraped = 0

    # Calculate effective end_page if max_pages is specified
    if max_pages is not None:
        effective_end_page = start_page + max_pages - 1
        if end_page is not None:
            effective_end_page = min(effective_end_page, end_page)
    else:
        effective_end_page = end_page

    if verbose:
        if effective_end_page:
            print(f"Scraping pages {start_page} to {effective_end_page}")
        else:
            print(f"Scraping from page {start_page} onwards")

    # Create progress bar - using tqdm.notebook for Jupyter compatibility
    pbar = tqdm(desc="Scraping pages", unit="page")

    try:
        while True:
            url = f"{base_url}?page={page_number}"
            if verbose:
                pbar.set_description(f"Page {page_number}")

            reviews = get_reviews_from_page(url)

            if not reviews:
                empty_pages += 1
                if verbose:
                    print(f"No reviews found on page {page_number} (Empty pages: {empty_pages}/{max_empty_pages})")

                if empty_pages >= max_empty_pages:
                    if verbose:
                        print(f"Stopping after {max_empty_pages} consecutive empty pages")
                    break

                # Try next page anyway
                page_number += 1
                pages_scraped += 1
                pbar.update(1)

                # Check if we've reached the end page
                if effective_end_page and page_number > effective_end_page:
                    if verbose:
                        print(f"Reached end page {effective_end_page}")
                    break

                # Add a delay between requests
                time.sleep(2)
                continue

            # Reset empty pages counter when we get results
            empty_pages = 0

            page_reviews_count = len(reviews)
            total_reviews += page_reviews_count

            if verbose:
                print(f"Found {page_reviews_count} reviews on page {page_number}")

            for review in reviews:
                try:
                    # Handle possible missing fields with .get()
                    data = {
                        'Page': review.get('_page_number', page_number),
                        'Date': pd.to_datetime(review.get("dates", {}).get("publishedDate")).strftime("%Y-%m-%d")
                               if review.get("dates", {}).get("publishedDate") else None,
                        'Author': review.get("consumer", {}).get("displayName", "Anonymous"),
                        'Body': review.get("text", ""),
                        'Heading': review.get("title", ""),
                        'Rating': review.get("rating"),
                        'Location': review.get("consumer", {}).get("countryCode", "")
                    }
                    reviews_data.append(data)
                except Exception as e:
                    if verbose:
                        print(f"Error processing a review: {e}")

            # Update progress info
            pbar.update(1)
            pages_scraped += 1
            pbar.set_postfix({"Reviews on page": page_reviews_count, "Total reviews": total_reviews})

            page_number += 1

            # Break if we've reached the end page
            if effective_end_page and page_number > effective_end_page:
                if verbose:
                    print(f"Reached end page {effective_end_page}")
                break

            # Add a delay between requests
            time.sleep(2)

    finally:
        # Always close the progress bar
        pbar.close()

    # Remove duplicates
    if reviews_data:
        original_count = len(reviews_data)
        df = pd.DataFrame(reviews_data)
        df.drop_duplicates(subset=['Body', 'Date', 'Author'], inplace=True)
        reviews_data = df.to_dict('records')
        duplicate_count = original_count - len(reviews_data)

        if verbose:
            print(f"\nScraping summary:")
            print(f"- Pages scraped: {pages_scraped}")
            print(f"- Page range: {start_page} to {page_number - 1}")
            print(f"- Raw reviews: {original_count}")
            print(f"- Duplicates removed: {duplicate_count}")
            print(f"- Final unique reviews: {len(reviews_data)}")

    return reviews_data

# Function to scrape in batches
def scrape_in_batches(base_url, batch_size=10, start_from=1, end_at=None):
    """
    Scrape Trustpilot reviews in batches of pages

    Parameters:
    - base_url: The base URL of the Trustpilot page
    - batch_size: Number of pages in each batch
    - start_from: First page to start scraping from
    - end_at: Last page to scrape (inclusive)
    """
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    all_reviews = []

    batch_start = start_from
    batch_num = 1

    # Create a master progress bar for batch tracking
    batches_to_process = (end_at - start_from + 1) // batch_size + 1 if end_at else None

    if batches_to_process:
        master_pbar = tqdm(total=batches_to_process, desc="Processing batches", unit="batch")
    else:
        master_pbar = tqdm(desc="Processing batches", unit="batch")

    try:
        while True:
            batch_end = batch_start + batch_size - 1
            if end_at and batch_end > end_at:
                batch_end = end_at

            print(f"\n{'='*50}")
            print(f"PROCESSING BATCH #{batch_num}: Pages {batch_start}-{batch_end}")
            print(f"{'='*50}")

            batch_reviews = scrape_trustpilot_reviews(
                base_url,
                start_page=batch_start,
                end_page=batch_end
            )

            if batch_reviews:
                all_reviews.extend(batch_reviews)

                # Save this batch
                batch_df = pd.DataFrame(batch_reviews)
                batch_filename = f"{batch_folder}/firstport_reviews_batch{batch_num}_p{batch_start}-p{batch_end}_{timestamp}.csv"
                batch_df.to_csv(batch_filename, index=False)
                print(f"Saved batch #{batch_num} with {len(batch_reviews)} reviews to {batch_filename}")

                # Also save cumulative results
                all_df = pd.DataFrame(all_reviews)
                cumulative_filename = f"{batch_folder}/firstport_reviews_cumulative_{timestamp}.csv"
                all_df.to_csv(cumulative_filename, index=False)
                print(f"Updated cumulative results with {len(all_reviews)} total reviews")
            else:
                print(f"No reviews found in batch #{batch_num} (pages {batch_start}-{batch_end})")
                if batch_start > start_from:  # If not the first batch
                    print("Stopping batch processing as no more reviews were found")
                    break

            # Move to next batch
            batch_start = batch_end + 1
            batch_num += 1

            # Update master progress bar
            master_pbar.update(1)

            # Break if we've reached the end
            if end_at and batch_start > end_at:
                print(f"Reached specified end page ({end_at})")
                break

            print("\nPausing between batches (5 seconds)...")
            time.sleep(5)  # Longer pause between batches

    finally:
        # Always close the master progress bar
        master_pbar.close()

    return all_reviews

# Scrap

In [ ]:
# Create a folder for batch results
batch_folder = "firstport_reviews_batches"
os.makedirs(batch_folder, exist_ok=True)

In [ ]:

# Base URL for FirstPort on Trustpilot
BASE_URL = "https://www.trustpilot.com/review/www.firstport.co.uk"

# Example usage:
# 1. Scrape pages 1-10 as a single batch
# reviews = scrape_trustpilot_reviews(BASE_URL, start_page=1, end_page=10)

# 2. Scrape in batches of 20 pages, from page 1 to 100
reviews = scrape_in_batches(BASE_URL, batch_size=20, start_from=1, end_at=807)

# Create final DataFrame
df = pd.DataFrame(reviews)

Processing batches:   0%|          | 0/41 [00:00<?, ?batch/s]

==================================================
PROCESSING BATCH #1: Pages 1-20
==================================================
Scraping pages 1 to 20

Scraping pages: 0page [00:00, ?page/s]

Found 20 reviews on page 1
Found 20 reviews on page 2
Found 20 reviews on page 3
Found 20 reviews on page 4
Found 20 reviews on page 5
Found 20 reviews on page 6
Found 20 reviews on page 7
Found 20 reviews on page 8
Found 20 reviews on page 9
Found 20 reviews on page 10
Found 20 reviews on page 11
Found 20 reviews on page 12
Found 20 reviews on page 13
Found 20 reviews on page 14
Found 20 reviews on page 15
Found 20 reviews on page 16
Found 20 reviews on page 17
Found 20 reviews on page 18
Found 20 reviews on page 19
Found 20 reviews on page 20
Reached end page 20

Scraping summary:
- Pages scraped: 20
- Page range: 1 to 20
- Raw reviews: 400
- Duplicates removed: 0
- Final unique reviews: 400
Saved batch #1 with 400 reviews to firstport_reviews_batches/firstport_reviews_batch1_p1-p20_20250427_064739.csv
Updated cumulative results with 400 total reviews

Pausing between batches (5 seconds)...

==================================================
PROCESSING BATCH #2: Pages 21-40
==================================================
Scraping pages 21 to 40

Scraping pages: 0page [00:00, ?page/s]

Found 20 reviews on page 21
Found 20 reviews on page 22
Found 20 reviews on page 23
Found 20 reviews on page 24
Found 20 reviews on page 25
Found 20 reviews on page 26
Found 20 reviews on page 27
Found 20 reviews on page 28
Found 20 reviews on page 29
Found 20 reviews on page 30
Found 20 reviews on page 31
Found 20 reviews on page 32
Found 20 reviews on page 33
Found 20 reviews on page 34
Found 20 reviews on page 35
Found 20 reviews on page 36
Found 20 reviews on page 37
Found 20 reviews on page 38
Found 20 reviews on page 39
Found 20 reviews on page 40
Reached end page 40

Scraping summary:
- Pages scraped: 20
- Page range: 21 to 40
- Raw reviews: 400
- Duplicates removed: 0
- Final unique reviews: 400
Saved batch #2 with 400 reviews to firstport_reviews_batches/firstport_reviews_batch2_p21-p40_20250427_064739.csv
Updated cumulative results with 800 total reviews

Pausing between batches (5 seconds)...

==================================================
PROCESSING BATCH #3: Pages 41-60
==================================================
Scraping pages 41 to 60

Scraping pages: 0page [00:00, ?page/s]

Found 20 reviews on page 41
Found 20 reviews on page 42
Found 20 reviews on page 43
Found 20 reviews on page 44
Found 20 reviews on page 45
Found 20 reviews on page 46
Found 20 reviews on page 47
Found 20 reviews on page 48
Found 20 reviews on page 49
Found 20 reviews on page 50
Found 20 reviews on page 51
Found 20 reviews on page 52
Found 20 reviews on page 53
Found 20 reviews on page 54
Found 20 reviews on page 55
Found 20 reviews on page 56
Found 20 reviews on page 57
Found 20 reviews on page 58
Found 20 reviews on page 59
Found 20 reviews on page 60
Reached end page 60

Scraping summary:
- Pages scraped: 20
- Page range: 41 to 60
- Raw reviews: 400
- Duplicates removed: 0
- Final unique reviews: 400
Saved batch #3 with 400 reviews to firstport_reviews_batches/firstport_reviews_batch3_p41-p60_20250427_064739.csv
Updated cumulative results with 1200 total reviews

Pausing between batches (5 seconds)...

==================================================
PROCESSING BATCH #4: Pages 61-80
==================================================
Scraping pages 61 to 80

Scraping pages: 0page [00:00, ?page/s]

Found 20 reviews on page 61
Found 20 reviews on page 62
Found 20 reviews on page 63
Found 20 reviews on page 64
Found 20 reviews on page 65
Found 20 reviews on page 66
Found 20 reviews on page 67
Found 20 reviews on page 68
Found 20 reviews on page 69
Found 20 reviews on page 70
Found 20 reviews on page 71
Found 20 reviews on page 72
Found 20 reviews on page 73
Found 20 reviews on page 74
Found 20 reviews on page 75
Found 20 reviews on page 76
Found 20 reviews on page 77
Found 20 reviews on page 78
Found 20 reviews on page 79
Found 20 reviews on page 80
Reached end page 80

Scraping summary:
- Pages scraped: 20
- Page range: 61 to 80
- Raw reviews: 400
- Duplicates removed: 0
- Final unique reviews: 400
Saved batch #4 with 400 reviews to firstport_reviews_batches/firstport_reviews_batch4_p61-p80_20250427_064739.csv
Updated cumulative results with 1600 total reviews

Pausing between batches (5 seconds)...

==================================================
PROCESSING BATCH #5: Pages 81-100
==================================================
Scraping pages 81 to 100

Scraping pages: 0page [00:00, ?page/s]

Found 20 reviews on page 81
Found 20 reviews on page 82
Found 20 reviews on page 83
Found 20 reviews on page 84
Found 20 reviews on page 85
Found 20 reviews on page 86
Found 20 reviews on page 87
Found 20 reviews on page 88
Found 20 reviews on page 89
Found 20 reviews on page 90
Found 20 reviews on page 91
Found 20 reviews on page 92
Found 20 reviews on page 93
Found 20 reviews on page 94
Found 20 reviews on page 95
Found 20 reviews on page 96
Found 20 reviews on page 97
Found 20 reviews on page 98
Found 20 reviews on page 99
Found 20 reviews on page 100
Reached end page 100

Scraping summary:
- Pages scraped: 20
- Page range: 81 to 100
- Raw reviews: 400
- Duplicates removed: 0
- Final unique reviews: 400
Saved batch #5 with 400 reviews to firstport_reviews_batches/firstport_reviews_batch5_p81-p100_20250427_064739.csv
Updated cumulative results with 2000 total reviews

Pausing between batches (5 seconds)...

==================================================
PROCESSING BATCH #6: Pages 101-120
==================================================
Scraping pages 101 to 120

Scraping pages: 0page [00:00, ?page/s]

Found 20 reviews on page 101
Found 20 reviews on page 102
Found 20 reviews on page 103
Found 20 reviews on page 104
Found 20 reviews on page 105
Found 20 reviews on page 106
Found 20 reviews on page 107
Found 20 reviews on page 108
Found 20 reviews on page 109
Found 20 reviews on page 110
Found 20 reviews on page 111
Found 20 reviews on page 112
Found 20 reviews on page 113
Found 20 reviews on page 114
Found 20 reviews on page 115
Found 20 reviews on page 116
Found 20 reviews on page 117
Found 20 reviews on page 118
Found 20 reviews on page 119
Found 20 reviews on page 120
Reached end page 120

Scraping summary:
- Pages scraped: 20
- Page range: 101 to 120
- Raw reviews: 400
- Duplicates removed: 0
- Final unique reviews: 400
Saved batch #6 with 400 reviews to firstport_reviews_batches/firstport_reviews_batch6_p101-p120_20250427_064739.csv
Updated cumulative results with 2400 total reviews

Pausing between batches (5 seconds)...

==================================================
PROCESSING BATCH #7: Pages 121-140
==================================================
Scraping pages 121 to 140

Scraping pages: 0page [00:00, ?page/s]

Found 20 reviews on page 121
Found 20 reviews on page 122
Found 20 reviews on page 123
Found 20 reviews on page 124
Found 20 reviews on page 125
Found 20 reviews on page 126
Found 20 reviews on page 127
Found 20 reviews on page 128
Found 20 reviews on page 129
Found 20 reviews on page 130
Found 20 reviews on page 131
Found 20 reviews on page 132
Found 20 reviews on page 133
Found 20 reviews on page 134
Found 20 reviews on page 135
Found 20 reviews on page 136
Found 20 reviews on page 137
Found 20 reviews on page 138
Found 20 reviews on page 139
Found 20 reviews on page 140
Reached end page 140

Scraping summary:
- Pages scraped: 20
- Page range: 121 to 140
- Raw reviews: 400
- Duplicates removed: 0
- Final unique reviews: 400
Saved batch #7 with 400 reviews to firstport_reviews_batches/firstport_reviews_batch7_p121-p140_20250427_064739.csv
Updated cumulative results with 2800 total reviews

Pausing between batches (5 seconds)...

==================================================
PROCESSING BATCH #8: Pages 141-160
==================================================
Scraping pages 141 to 160

Scraping pages: 0page [00:00, ?page/s]

Found 20 reviews on page 141
Found 20 reviews on page 142
Found 20 reviews on page 143
Found 20 reviews on page 144
Found 20 reviews on page 145
Found 20 reviews on page 146
Found 20 reviews on page 147
Found 20 reviews on page 148
Found 20 reviews on page 149
Found 20 reviews on page 150
Found 20 reviews on page 151
Found 20 reviews on page 152
Found 20 reviews on page 153
Found 20 reviews on page 154
Found 20 reviews on page 155
Found 20 reviews on page 156
Found 20 reviews on page 157
Found 20 reviews on page 158
Found 20 reviews on page 159
Found 20 reviews on page 160
Reached end page 160

Scraping summary:
- Pages scraped: 20
- Page range: 141 to 160
- Raw reviews: 400
- Duplicates removed: 0
- Final unique reviews: 400
Saved batch #8 with 400 reviews to firstport_reviews_batches/firstport_reviews_batch8_p141-p160_20250427_064739.csv
Updated cumulative results with 3200 total reviews

Pausing between batches (5 seconds)...

==================================================
PROCESSING BATCH #9: Pages 161-180
==================================================
Scraping pages 161 to 180

Scraping pages: 0page [00:00, ?page/s]

Found 20 reviews on page 161
Found 20 reviews on page 162
Found 20 reviews on page 163
Found 20 reviews on page 164
Found 20 reviews on page 165
Found 20 reviews on page 166
Found 20 reviews on page 167
Found 20 reviews on page 168
Found 20 reviews on page 169
Found 20 reviews on page 170
Found 20 reviews on page 171
Found 20 reviews on page 172
Found 20 reviews on page 173
Found 20 reviews on page 174
Found 20 reviews on page 175
Found 20 reviews on page 176
Found 20 reviews on page 177
Found 20 reviews on page 178
Found 20 reviews on page 179
Found 20 reviews on page 180
Reached end page 180

Scraping summary:
- Pages scraped: 20
- Page range: 161 to 180
- Raw reviews: 400
- Duplicates removed: 0
- Final unique reviews: 400
Saved batch #9 with 400 reviews to firstport_reviews_batches/firstport_reviews_batch9_p161-p180_20250427_064739.csv
Updated cumulative results with 3600 total reviews

Pausing between batches (5 seconds)...

==================================================
PROCESSING BATCH #10: Pages 181-200
==================================================
Scraping pages 181 to 200

Scraping pages: 0page [00:00, ?page/s]

Found 20 reviews on page 181
Found 20 reviews on page 182
Found 20 reviews on page 183
Found 20 reviews on page 184
Found 20 reviews on page 185
Found 20 reviews on page 186
Found 20 reviews on page 187
Found 20 reviews on page 188
Found 20 reviews on page 189
Found 20 reviews on page 190
Found 20 reviews on page 191
Found 20 reviews on page 192
Found 20 reviews on page 193
Found 20 reviews on page 194
Found 20 reviews on page 195
Found 20 reviews on page 196
Found 20 reviews on page 197
Found 20 reviews on page 198
Found 20 reviews on page 199
Found 20 reviews on page 200
Reached end page 200

Scraping summary:
- Pages scraped: 20
- Page range: 181 to 200
- Raw reviews: 400
- Duplicates removed: 0
- Final unique reviews: 400
Saved batch #10 with 400 reviews to firstport_reviews_batches/firstport_reviews_batch10_p181-p200_20250427_064739.csv
Updated cumulative results with 4000 total reviews

Pausing between batches (5 seconds)...

==================================================
PROCESSING BATCH #11: Pages 201-220
==================================================
Scraping pages 201 to 220

Scraping pages: 0page [00:00, ?page/s]

Found 20 reviews on page 201
Found 20 reviews on page 202
Found 20 reviews on page 203
Found 20 reviews on page 204
Found 20 reviews on page 205
Found 20 reviews on page 206
Found 20 reviews on page 207
Found 20 reviews on page 208
Found 20 reviews on page 209
Found 20 reviews on page 210
Found 20 reviews on page 211
Found 20 reviews on page 212
Found 20 reviews on page 213
Found 20 reviews on page 214
Found 20 reviews on page 215
Found 20 reviews on page 216
Found 20 reviews on page 217
Found 20 reviews on page 218
Found 20 reviews on page 219
Found 20 reviews on page 220
Reached end page 220

Scraping summary:
- Pages scraped: 20
- Page range: 201 to 220
- Raw reviews: 400
- Duplicates removed: 0
- Final unique reviews: 400
Saved batch #11 with 400 reviews to firstport_reviews_batches/firstport_reviews_batch11_p201-p220_20250427_064739.csv
Updated cumulative results with 4400 total reviews

Pausing between batches (5 seconds)...

==================================================
PROCESSING BATCH #12: Pages 221-240
==================================================
Scraping pages 221 to 240

Scraping pages: 0page [00:00, ?page/s]

Found 20 reviews on page 221
Found 20 reviews on page 222
Found 20 reviews on page 223
Found 20 reviews on page 224
Found 20 reviews on page 225
Found 20 reviews on page 226
Found 20 reviews on page 227
Found 20 reviews on page 228
Found 20 reviews on page 229
Found 20 reviews on page 230
Found 20 reviews on page 231
Found 20 reviews on page 232
Found 20 reviews on page 233
Found 20 reviews on page 234
Found 20 reviews on page 235
Found 20 reviews on page 236
Found 20 reviews on page 237
Found 20 reviews on page 238
Found 20 reviews on page 239
Found 20 reviews on page 240
Reached end page 240

Scraping summary:
- Pages scraped: 20
- Page range: 221 to 240
- Raw reviews: 400
- Duplicates removed: 0
- Final unique reviews: 400
Saved batch #12 with 400 reviews to firstport_reviews_batches/firstport_reviews_batch12_p221-p240_20250427_064739.csv
Updated cumulative results with 4800 total reviews

Pausing between batches (5 seconds)...

==================================================
PROCESSING BATCH #13: Pages 241-260
==================================================
Scraping pages 241 to 260

Scraping pages: 0page [00:00, ?page/s]

Found 20 reviews on page 241
Found 20 reviews on page 242
Found 20 reviews on page 243
Found 20 reviews on page 244
Found 20 reviews on page 245
Found 20 reviews on page 246
Found 20 reviews on page 247
Found 20 reviews on page 248
Found 20 reviews on page 249
Found 20 reviews on page 250
Found 20 reviews on page 251
Found 20 reviews on page 252
Found 20 reviews on page 253
Found 20 reviews on page 254
Found 20 reviews on page 255
Found 20 reviews on page 256
Found 20 reviews on page 257
Found 20 reviews on page 258
Found 20 reviews on page 259
Found 20 reviews on page 260
Reached end page 260

Scraping summary:
- Pages scraped: 20
- Page range: 241 to 260
- Raw reviews: 400
- Duplicates removed: 0
- Final unique reviews: 400
Saved batch #13 with 400 reviews to firstport_reviews_batches/firstport_reviews_batch13_p241-p260_20250427_064739.csv
Updated cumulative results with 5200 total reviews

Pausing between batches (5 seconds)...

==================================================
PROCESSING BATCH #14: Pages 261-280
==================================================
Scraping pages 261 to 280

Scraping pages: 0page [00:00, ?page/s]

Found 20 reviews on page 261
Found 20 reviews on page 262
Found 20 reviews on page 263
Found 20 reviews on page 264
Found 20 reviews on page 265
Found 20 reviews on page 266
Found 20 reviews on page 267
Found 20 reviews on page 268
Found 20 reviews on page 269
Found 20 reviews on page 270
Found 20 reviews on page 271
Found 20 reviews on page 272
Found 20 reviews on page 273
Found 20 reviews on page 274
Found 20 reviews on page 275
Found 20 reviews on page 276
Found 20 reviews on page 277
Found 20 reviews on page 278
Found 20 reviews on page 279
Found 20 reviews on page 280
Reached end page 280

Scraping summary:
- Pages scraped: 20
- Page range: 261 to 280
- Raw reviews: 400
- Duplicates removed: 0
- Final unique reviews: 400
Saved batch #14 with 400 reviews to firstport_reviews_batches/firstport_reviews_batch14_p261-p280_20250427_064739.csv
Updated cumulative results with 5600 total reviews

Pausing between batches (5 seconds)...

==================================================
PROCESSING BATCH #15: Pages 281-300
==================================================
Scraping pages 281 to 300

Scraping pages: 0page [00:00, ?page/s]

Found 20 reviews on page 281
Found 20 reviews on page 282
Found 20 reviews on page 283
Found 20 reviews on page 284
Found 20 reviews on page 285
Found 20 reviews on page 286
Found 20 reviews on page 287
Found 20 reviews on page 288
Found 20 reviews on page 289
Found 20 reviews on page 290
Found 20 reviews on page 291
Found 20 reviews on page 292
Found 20 reviews on page 293
Found 20 reviews on page 294
Found 20 reviews on page 295
Found 20 reviews on page 296
Found 20 reviews on page 297
Found 20 reviews on page 298
Found 20 reviews on page 299
Found 20 reviews on page 300
Reached end page 300

Scraping summary:
- Pages scraped: 20
- Page range: 281 to 300
- Raw reviews: 400
- Duplicates removed: 0
- Final unique reviews: 400
Saved batch #15 with 400 reviews to firstport_reviews_batches/firstport_reviews_batch15_p281-p300_20250427_064739.csv
Updated cumulative results with 6000 total reviews

Pausing between batches (5 seconds)...

==================================================
PROCESSING BATCH #16: Pages 301-320
==================================================
Scraping pages 301 to 320

Scraping pages: 0page [00:00, ?page/s]

Found 20 reviews on page 301
Found 20 reviews on page 302
Found 20 reviews on page 303
Found 20 reviews on page 304
Found 20 reviews on page 305
Found 20 reviews on page 306
Found 20 reviews on page 307
Found 20 reviews on page 308
Found 20 reviews on page 309
Found 20 reviews on page 310
Found 20 reviews on page 311
Found 20 reviews on page 312
Found 20 reviews on page 313
Found 20 reviews on page 314
Found 20 reviews on page 315
Found 20 reviews on page 316
Found 20 reviews on page 317
Found 20 reviews on page 318
Found 20 reviews on page 319
Found 20 reviews on page 320
Reached end page 320

Scraping summary:
- Pages scraped: 20
- Page range: 301 to 320
- Raw reviews: 400
- Duplicates removed: 0
- Final unique reviews: 400
Saved batch #16 with 400 reviews to firstport_reviews_batches/firstport_reviews_batch16_p301-p320_20250427_064739.csv
Updated cumulative results with 6400 total reviews

Pausing between batches (5 seconds)...

==================================================
PROCESSING BATCH #17: Pages 321-340
==================================================
Scraping pages 321 to 340

Scraping pages: 0page [00:00, ?page/s]

Found 20 reviews on page 321
Found 20 reviews on page 322
Found 20 reviews on page 323
Found 20 reviews on page 324
Found 20 reviews on page 325
Found 20 reviews on page 326
Found 20 reviews on page 327
Found 20 reviews on page 328
Found 20 reviews on page 329
Found 20 reviews on page 330
Found 20 reviews on page 331
Found 20 reviews on page 332
Found 20 reviews on page 333
Found 20 reviews on page 334
Found 20 reviews on page 335
Found 20 reviews on page 336
Found 20 reviews on page 337
Found 20 reviews on page 338
Found 20 reviews on page 339
Found 20 reviews on page 340
Reached end page 340

Scraping summary:
- Pages scraped: 20
- Page range: 321 to 340
- Raw reviews: 400
- Duplicates removed: 0
- Final unique reviews: 400
Saved batch #17 with 400 reviews to firstport_reviews_batches/firstport_reviews_batch17_p321-p340_20250427_064739.csv
Updated cumulative results with 6800 total reviews

Pausing between batches (5 seconds)...

==================================================
PROCESSING BATCH #18: Pages 341-360
==================================================
Scraping pages 341 to 360

Scraping pages: 0page [00:00, ?page/s]

Found 20 reviews on page 341
Found 20 reviews on page 342
Found 20 reviews on page 343
Found 20 reviews on page 344
Found 20 reviews on page 345
Found 20 reviews on page 346
Found 20 reviews on page 347
Found 20 reviews on page 348
Found 20 reviews on page 349
Found 20 reviews on page 350
Found 20 reviews on page 351
Found 20 reviews on page 352
Found 20 reviews on page 353
Found 20 reviews on page 354
Found 20 reviews on page 355
Found 20 reviews on page 356
Found 20 reviews on page 357
Found 20 reviews on page 358
Found 20 reviews on page 359
Found 20 reviews on page 360
Reached end page 360

Scraping summary:
- Pages scraped: 20
- Page range: 341 to 360
- Raw reviews: 400
- Duplicates removed: 0
- Final unique reviews: 400
Saved batch #18 with 400 reviews to firstport_reviews_batches/firstport_reviews_batch18_p341-p360_20250427_064739.csv
Updated cumulative results with 7200 total reviews

Pausing between batches (5 seconds)...

==================================================
PROCESSING BATCH #19: Pages 361-380
==================================================
Scraping pages 361 to 380

Scraping pages: 0page [00:00, ?page/s]

Found 20 reviews on page 361
Found 20 reviews on page 362
Found 20 reviews on page 363
Found 20 reviews on page 364
Found 20 reviews on page 365
Found 20 reviews on page 366
Found 20 reviews on page 367
Found 20 reviews on page 368
Found 20 reviews on page 369
Found 20 reviews on page 370
Found 20 reviews on page 371
Found 20 reviews on page 372
Found 20 reviews on page 373
Found 20 reviews on page 374
Found 20 reviews on page 375
Found 20 reviews on page 376
Found 20 reviews on page 377
Found 20 reviews on page 378
Found 20 reviews on page 379
Found 20 reviews on page 380
Reached end page 380

Scraping summary:
- Pages scraped: 20
- Page range: 361 to 380
- Raw reviews: 400
- Duplicates removed: 0
- Final unique reviews: 400
Saved batch #19 with 400 reviews to firstport_reviews_batches/firstport_reviews_batch19_p361-p380_20250427_064739.csv
Updated cumulative results with 7600 total reviews

Pausing between batches (5 seconds)...

==================================================
PROCESSING BATCH #20: Pages 381-400
==================================================
Scraping pages 381 to 400

Scraping pages: 0page [00:00, ?page/s]

Found 20 reviews on page 381
Found 20 reviews on page 382
Found 20 reviews on page 383
Found 20 reviews on page 384
Found 20 reviews on page 385
Found 20 reviews on page 386
Found 20 reviews on page 387
Found 20 reviews on page 388
Found 20 reviews on page 389
Found 20 reviews on page 390
Found 20 reviews on page 391
Found 20 reviews on page 392
Found 20 reviews on page 393
Found 20 reviews on page 394
Found 20 reviews on page 395
Found 20 reviews on page 396
Found 20 reviews on page 397
Found 20 reviews on page 398
Found 20 reviews on page 399
Found 20 reviews on page 400
Reached end page 400

Scraping summary:
- Pages scraped: 20
- Page range: 381 to 400
- Raw reviews: 400
- Duplicates removed: 0
- Final unique reviews: 400
Saved batch #20 with 400 reviews to firstport_reviews_batches/firstport_reviews_batch20_p381-p400_20250427_064739.csv
Updated cumulative results with 8000 total reviews

Pausing between batches (5 seconds)...

==================================================
PROCESSING BATCH #21: Pages 401-420
==================================================
Scraping pages 401 to 420

Scraping pages: 0page [00:00, ?page/s]

Found 20 reviews on page 401
Found 20 reviews on page 402
Found 20 reviews on page 403
Found 20 reviews on page 404
Found 20 reviews on page 405
Found 20 reviews on page 406
Found 20 reviews on page 407
Found 20 reviews on page 408
Found 20 reviews on page 409
Found 20 reviews on page 410
Found 20 reviews on page 411
Found 20 reviews on page 412
Found 20 reviews on page 413
Found 20 reviews on page 414
Found 20 reviews on page 415
Found 20 reviews on page 416
Found 20 reviews on page 417
Found 20 reviews on page 418
Found 20 reviews on page 419
Found 20 reviews on page 420
Reached end page 420

Scraping summary:
- Pages scraped: 20
- Page range: 401 to 420
- Raw reviews: 400
- Duplicates removed: 0
- Final unique reviews: 400
Saved batch #21 with 400 reviews to firstport_reviews_batches/firstport_reviews_batch21_p401-p420_20250427_064739.csv
Updated cumulative results with 8400 total reviews

Pausing between batches (5 seconds)...

==================================================
PROCESSING BATCH #22: Pages 421-440
==================================================
Scraping pages 421 to 440

Scraping pages: 0page [00:00, ?page/s]

Found 20 reviews on page 421
Found 20 reviews on page 422
Found 20 reviews on page 423
Found 20 reviews on page 424
Found 20 reviews on page 425
Found 20 reviews on page 426
Found 20 reviews on page 427
Found 20 reviews on page 428
Found 20 reviews on page 429
Found 20 reviews on page 430
Found 20 reviews on page 431
Found 20 reviews on page 432
Found 20 reviews on page 433
Found 20 reviews on page 434
Found 20 reviews on page 435
Found 20 reviews on page 436
Found 20 reviews on page 437
Found 20 reviews on page 438
Found 20 reviews on page 439
Found 20 reviews on page 440
Reached end page 440

Scraping summary:
- Pages scraped: 20
- Page range: 421 to 440
- Raw reviews: 400
- Duplicates removed: 0
- Final unique reviews: 400
Saved batch #22 with 400 reviews to firstport_reviews_batches/firstport_reviews_batch22_p421-p440_20250427_064739.csv
Updated cumulative results with 8800 total reviews

Pausing between batches (5 seconds)...

==================================================
PROCESSING BATCH #23: Pages 441-460
==================================================
Scraping pages 441 to 460

Scraping pages: 0page [00:00, ?page/s]

Found 20 reviews on page 441
Found 20 reviews on page 442
Found 20 reviews on page 443
Found 20 reviews on page 444
Found 20 reviews on page 445
Found 20 reviews on page 446
Found 20 reviews on page 447
Found 20 reviews on page 448
Found 20 reviews on page 449
Found 20 reviews on page 450
Found 20 reviews on page 451
Found 20 reviews on page 452
Found 20 reviews on page 453
Found 20 reviews on page 454
Found 20 reviews on page 455
Found 20 reviews on page 456
Found 20 reviews on page 457
Found 20 reviews on page 458
Found 20 reviews on page 459
Found 20 reviews on page 460
Reached end page 460

Scraping summary:
- Pages scraped: 20
- Page range: 441 to 460
- Raw reviews: 400
- Duplicates removed: 0
- Final unique reviews: 400
Saved batch #23 with 400 reviews to firstport_reviews_batches/firstport_reviews_batch23_p441-p460_20250427_064739.csv
Updated cumulative results with 9200 total reviews

Pausing between batches (5 seconds)...

==================================================
PROCESSING BATCH #24: Pages 461-480
==================================================
Scraping pages 461 to 480

Scraping pages: 0page [00:00, ?page/s]

Found 20 reviews on page 461
Found 20 reviews on page 462
Found 20 reviews on page 463
Found 20 reviews on page 464
Found 20 reviews on page 465
Found 20 reviews on page 466
Found 20 reviews on page 467
Found 20 reviews on page 468
Found 20 reviews on page 469
Found 20 reviews on page 470
Found 20 reviews on page 471
Found 20 reviews on page 472
Found 20 reviews on page 473
Found 20 reviews on page 474
Found 20 reviews on page 475
Found 20 reviews on page 476
Found 20 reviews on page 477
Found 20 reviews on page 478
Found 20 reviews on page 479
Found 20 reviews on page 480
Reached end page 480

Scraping summary:
- Pages scraped: 20
- Page range: 461 to 480
- Raw reviews: 400
- Duplicates removed: 0
- Final unique reviews: 400
Saved batch #24 with 400 reviews to firstport_reviews_batches/firstport_reviews_batch24_p461-p480_20250427_064739.csv
Updated cumulative results with 9600 total reviews

Pausing between batches (5 seconds)...

==================================================
PROCESSING BATCH #25: Pages 481-500
==================================================
Scraping pages 481 to 500

Scraping pages: 0page [00:00, ?page/s]

Found 20 reviews on page 481
Found 20 reviews on page 482
Found 20 reviews on page 483
Found 20 reviews on page 484
Found 20 reviews on page 485
Found 20 reviews on page 486
Found 20 reviews on page 487
Found 20 reviews on page 488
Found 20 reviews on page 489
Found 20 reviews on page 490
Found 20 reviews on page 491
Found 20 reviews on page 492
Found 20 reviews on page 493
Found 20 reviews on page 494
Found 20 reviews on page 495
Found 20 reviews on page 496
Found 20 reviews on page 497
Found 20 reviews on page 498
Found 20 reviews on page 499
Found 20 reviews on page 500
Reached end page 500

Scraping summary:
- Pages scraped: 20
- Page range: 481 to 500
- Raw reviews: 400
- Duplicates removed: 0
- Final unique reviews: 400
Saved batch #25 with 400 reviews to firstport_reviews_batches/firstport_reviews_batch25_p481-p500_20250427_064739.csv
Updated cumulative results with 10000 total reviews

Pausing between batches (5 seconds)...

==================================================
PROCESSING BATCH #26: Pages 501-520
==================================================
Scraping pages 501 to 520

Scraping pages: 0page [00:00, ?page/s]

Found 20 reviews on page 501
Found 20 reviews on page 502
Found 20 reviews on page 503
Found 20 reviews on page 504
Found 20 reviews on page 505
Found 20 reviews on page 506
Found 20 reviews on page 507
Found 20 reviews on page 508
Found 20 reviews on page 509
Found 20 reviews on page 510
Found 20 reviews on page 511
Found 20 reviews on page 512
Found 20 reviews on page 513
Found 20 reviews on page 514
Found 20 reviews on page 515
Found 20 reviews on page 516
Found 20 reviews on page 517
Found 20 reviews on page 518
Found 20 reviews on page 519
Found 20 reviews on page 520
Reached end page 520

Scraping summary:
- Pages scraped: 20
- Page range: 501 to 520
- Raw reviews: 400
- Duplicates removed: 0
- Final unique reviews: 400
Saved batch #26 with 400 reviews to firstport_reviews_batches/firstport_reviews_batch26_p501-p520_20250427_064739.csv
Updated cumulative results with 10400 total reviews

Pausing between batches (5 seconds)...

==================================================
PROCESSING BATCH #27: Pages 521-540
==================================================
Scraping pages 521 to 540

Scraping pages: 0page [00:00, ?page/s]

Found 20 reviews on page 521
Found 20 reviews on page 522
Found 20 reviews on page 523
Found 20 reviews on page 524
Found 20 reviews on page 525
Found 20 reviews on page 526
Found 20 reviews on page 527
Found 20 reviews on page 528
Found 20 reviews on page 529
Found 20 reviews on page 530
Found 20 reviews on page 531
Found 20 reviews on page 532
Found 20 reviews on page 533
Found 20 reviews on page 534
Found 20 reviews on page 535
Found 20 reviews on page 536
Found 20 reviews on page 537
Found 20 reviews on page 538
Found 20 reviews on page 539
Found 20 reviews on page 540
Reached end page 540

Scraping summary:
- Pages scraped: 20
- Page range: 521 to 540
- Raw reviews: 400
- Duplicates removed: 0
- Final unique reviews: 400
Saved batch #27 with 400 reviews to firstport_reviews_batches/firstport_reviews_batch27_p521-p540_20250427_064739.csv
Updated cumulative results with 10800 total reviews

Pausing between batches (5 seconds)...

==================================================
PROCESSING BATCH #28: Pages 541-560
==================================================
Scraping pages 541 to 560

Scraping pages: 0page [00:00, ?page/s]

Found 20 reviews on page 541
Found 20 reviews on page 542
Found 20 reviews on page 543
Found 20 reviews on page 544
Found 20 reviews on page 545
Found 20 reviews on page 546
Found 20 reviews on page 547
Found 20 reviews on page 548
Found 20 reviews on page 549
Found 20 reviews on page 550
Found 20 reviews on page 551
Found 20 reviews on page 552
Found 20 reviews on page 553
Found 20 reviews on page 554
Found 20 reviews on page 555
Found 20 reviews on page 556
Found 20 reviews on page 557
Found 20 reviews on page 558
Found 20 reviews on page 559
Found 20 reviews on page 560
Reached end page 560

Scraping summary:
- Pages scraped: 20
- Page range: 541 to 560
- Raw reviews: 400
- Duplicates removed: 0
- Final unique reviews: 400
Saved batch #28 with 400 reviews to firstport_reviews_batches/firstport_reviews_batch28_p541-p560_20250427_064739.csv
Updated cumulative results with 11200 total reviews

Pausing between batches (5 seconds)...

==================================================
PROCESSING BATCH #29: Pages 561-580
==================================================
Scraping pages 561 to 580

Scraping pages: 0page [00:00, ?page/s]

Found 20 reviews on page 561
Found 20 reviews on page 562
Found 20 reviews on page 563
Found 20 reviews on page 564
Found 20 reviews on page 565
Found 20 reviews on page 566
Found 20 reviews on page 567
Found 20 reviews on page 568
Found 20 reviews on page 569
Found 20 reviews on page 570
Found 20 reviews on page 571
Found 20 reviews on page 572
Found 20 reviews on page 573
Found 20 reviews on page 574
Found 20 reviews on page 575
Found 20 reviews on page 576
Found 20 reviews on page 577
Found 20 reviews on page 578
Found 20 reviews on page 579
Found 20 reviews on page 580
Reached end page 580

Scraping summary:
- Pages scraped: 20
- Page range: 561 to 580
- Raw reviews: 400
- Duplicates removed: 0
- Final unique reviews: 400
Saved batch #29 with 400 reviews to firstport_reviews_batches/firstport_reviews_batch29_p561-p580_20250427_064739.csv
Updated cumulative results with 11600 total reviews

Pausing between batches (5 seconds)...

==================================================
PROCESSING BATCH #30: Pages 581-600
==================================================
Scraping pages 581 to 600

Scraping pages: 0page [00:00, ?page/s]

Found 20 reviews on page 581
Found 20 reviews on page 582
Found 20 reviews on page 583
Found 20 reviews on page 584
Found 20 reviews on page 585
Found 20 reviews on page 586
Found 20 reviews on page 587
Found 20 reviews on page 588
Found 20 reviews on page 589
Found 20 reviews on page 590
Found 20 reviews on page 591
Found 20 reviews on page 592
Found 20 reviews on page 593
Found 20 reviews on page 594
Found 20 reviews on page 595
Found 20 reviews on page 596
Found 20 reviews on page 597
Found 20 reviews on page 598
Found 20 reviews on page 599
Found 20 reviews on page 600
Reached end page 600

Scraping summary:
- Pages scraped: 20
- Page range: 581 to 600
- Raw reviews: 400
- Duplicates removed: 0
- Final unique reviews: 400
Saved batch #30 with 400 reviews to firstport_reviews_batches/firstport_reviews_batch30_p581-p600_20250427_064739.csv
Updated cumulative results with 12000 total reviews

Pausing between batches (5 seconds)...

==================================================
PROCESSING BATCH #31: Pages 601-620
==================================================
Scraping pages 601 to 620

Scraping pages: 0page [00:00, ?page/s]

Found 20 reviews on page 601
Found 20 reviews on page 602
Found 20 reviews on page 603
Found 20 reviews on page 604
Found 20 reviews on page 605
Found 20 reviews on page 606
Found 20 reviews on page 607
Found 20 reviews on page 608
Found 20 reviews on page 609
Found 20 reviews on page 610
Found 20 reviews on page 611
Found 20 reviews on page 612
Found 20 reviews on page 613
Found 20 reviews on page 614
Found 20 reviews on page 615
Found 20 reviews on page 616
Found 20 reviews on page 617
Found 20 reviews on page 618
Found 20 reviews on page 619
Found 20 reviews on page 620
Reached end page 620

Scraping summary:
- Pages scraped: 20
- Page range: 601 to 620
- Raw reviews: 400
- Duplicates removed: 0
- Final unique reviews: 400
Saved batch #31 with 400 reviews to firstport_reviews_batches/firstport_reviews_batch31_p601-p620_20250427_064739.csv
Updated cumulative results with 12400 total reviews

Pausing between batches (5 seconds)...

==================================================
PROCESSING BATCH #32: Pages 621-640
==================================================
Scraping pages 621 to 640

Scraping pages: 0page [00:00, ?page/s]

Found 20 reviews on page 621
Found 20 reviews on page 622
Found 20 reviews on page 623
Found 20 reviews on page 624
Found 20 reviews on page 625
Found 20 reviews on page 626
Found 20 reviews on page 627
Found 20 reviews on page 628
Found 20 reviews on page 629
Found 20 reviews on page 630
Found 20 reviews on page 631
Found 20 reviews on page 632
Found 20 reviews on page 633
Found 20 reviews on page 634
Found 20 reviews on page 635
Found 20 reviews on page 636
Found 20 reviews on page 637
Found 20 reviews on page 638
Found 20 reviews on page 639
Found 20 reviews on page 640
Reached end page 640

Scraping summary:
- Pages scraped: 20
- Page range: 621 to 640
- Raw reviews: 400
- Duplicates removed: 0
- Final unique reviews: 400
Saved batch #32 with 400 reviews to firstport_reviews_batches/firstport_reviews_batch32_p621-p640_20250427_064739.csv
Updated cumulative results with 12800 total reviews

Pausing between batches (5 seconds)...

==================================================
PROCESSING BATCH #33: Pages 641-660
==================================================
Scraping pages 641 to 660

Scraping pages: 0page [00:00, ?page/s]

Found 20 reviews on page 641
Found 20 reviews on page 642
Found 20 reviews on page 643
Found 20 reviews on page 644
Found 20 reviews on page 645
Found 20 reviews on page 646
Found 20 reviews on page 647
Found 20 reviews on page 648
Found 20 reviews on page 649
Found 20 reviews on page 650
Found 20 reviews on page 651
Found 20 reviews on page 652
Found 20 reviews on page 653
Found 20 reviews on page 654
Found 20 reviews on page 655
Found 20 reviews on page 656
Found 20 reviews on page 657
Found 20 reviews on page 658
Found 20 reviews on page 659
Found 20 reviews on page 660
Reached end page 660

Scraping summary:
- Pages scraped: 20
- Page range: 641 to 660
- Raw reviews: 400
- Duplicates removed: 0
- Final unique reviews: 400
Saved batch #33 with 400 reviews to firstport_reviews_batches/firstport_reviews_batch33_p641-p660_20250427_064739.csv
Updated cumulative results with 13200 total reviews

Pausing between batches (5 seconds)...

==================================================
PROCESSING BATCH #34: Pages 661-680
==================================================
Scraping pages 661 to 680

Scraping pages: 0page [00:00, ?page/s]

Found 20 reviews on page 661
Found 20 reviews on page 662
Found 20 reviews on page 663
Found 20 reviews on page 664
Found 20 reviews on page 665
Found 20 reviews on page 666
Found 20 reviews on page 667
Found 20 reviews on page 668
Found 20 reviews on page 669
Found 20 reviews on page 670
Found 20 reviews on page 671
Found 20 reviews on page 672
Found 20 reviews on page 673
Found 20 reviews on page 674
Found 20 reviews on page 675
Found 20 reviews on page 676
Found 20 reviews on page 677
Found 20 reviews on page 678
Found 20 reviews on page 679
Found 20 reviews on page 680
Reached end page 680

Scraping summary:
- Pages scraped: 20
- Page range: 661 to 680
- Raw reviews: 400
- Duplicates removed: 0
- Final unique reviews: 400
Saved batch #34 with 400 reviews to firstport_reviews_batches/firstport_reviews_batch34_p661-p680_20250427_064739.csv
Updated cumulative results with 13600 total reviews

Pausing between batches (5 seconds)...

==================================================
PROCESSING BATCH #35: Pages 681-700
==================================================
Scraping pages 681 to 700

Scraping pages: 0page [00:00, ?page/s]

Found 20 reviews on page 681
Found 20 reviews on page 682
Found 20 reviews on page 683
Found 20 reviews on page 684
Found 20 reviews on page 685
Found 20 reviews on page 686
Found 20 reviews on page 687
Found 20 reviews on page 688
Found 20 reviews on page 689
Found 20 reviews on page 690
Found 20 reviews on page 691
Found 20 reviews on page 692
Found 20 reviews on page 693
Found 20 reviews on page 694
Found 20 reviews on page 695
Found 20 reviews on page 696
Found 20 reviews on page 697
Found 20 reviews on page 698
Found 20 reviews on page 699
Found 20 reviews on page 700
Reached end page 700

Scraping summary:
- Pages scraped: 20
- Page range: 681 to 700
- Raw reviews: 400
- Duplicates removed: 0
- Final unique reviews: 400
Saved batch #35 with 400 reviews to firstport_reviews_batches/firstport_reviews_batch35_p681-p700_20250427_064739.csv
Updated cumulative results with 14000 total reviews

Pausing between batches (5 seconds)...

==================================================
PROCESSING BATCH #36: Pages 701-720
==================================================
Scraping pages 701 to 720

Scraping pages: 0page [00:00, ?page/s]

Found 20 reviews on page 701
Found 20 reviews on page 702
Found 20 reviews on page 703
Found 20 reviews on page 704
Found 20 reviews on page 705
Found 20 reviews on page 706
Found 20 reviews on page 707
Found 20 reviews on page 708
Found 20 reviews on page 709
Found 20 reviews on page 710
Found 20 reviews on page 711
Found 20 reviews on page 712
Found 20 reviews on page 713
Found 20 reviews on page 714
Found 20 reviews on page 715
Found 20 reviews on page 716
Found 20 reviews on page 717
Found 20 reviews on page 718
Found 20 reviews on page 719
Found 20 reviews on page 720
Reached end page 720

Scraping summary:
- Pages scraped: 20
- Page range: 701 to 720
- Raw reviews: 400
- Duplicates removed: 0
- Final unique reviews: 400
Saved batch #36 with 400 reviews to firstport_reviews_batches/firstport_reviews_batch36_p701-p720_20250427_064739.csv
Updated cumulative results with 14400 total reviews

Pausing between batches (5 seconds)...

==================================================
PROCESSING BATCH #37: Pages 721-740
==================================================
Scraping pages 721 to 740

Scraping pages: 0page [00:00, ?page/s]

Found 20 reviews on page 721
Found 20 reviews on page 722
Found 20 reviews on page 723
Found 20 reviews on page 724
Found 20 reviews on page 725
Found 20 reviews on page 726
Found 20 reviews on page 727
Found 20 reviews on page 728
Found 20 reviews on page 729
Found 20 reviews on page 730
Found 20 reviews on page 731
Found 20 reviews on page 732
Found 20 reviews on page 733
Found 20 reviews on page 734
Found 20 reviews on page 735
Found 20 reviews on page 736
Found 20 reviews on page 737
Found 20 reviews on page 738
Found 20 reviews on page 739
Found 20 reviews on page 740
Reached end page 740

Scraping summary:
- Pages scraped: 20
- Page range: 721 to 740
- Raw reviews: 400
- Duplicates removed: 0
- Final unique reviews: 400
Saved batch #37 with 400 reviews to firstport_reviews_batches/firstport_reviews_batch37_p721-p740_20250427_064739.csv
Updated cumulative results with 14800 total reviews

Pausing between batches (5 seconds)...

==================================================
PROCESSING BATCH #38: Pages 741-760
==================================================
Scraping pages 741 to 760

Scraping pages: 0page [00:00, ?page/s]

Found 20 reviews on page 741
Found 20 reviews on page 742
Found 20 reviews on page 743
Found 20 reviews on page 744
Found 20 reviews on page 745
Found 20 reviews on page 746
Found 20 reviews on page 747
Found 20 reviews on page 748
Found 20 reviews on page 749
Found 20 reviews on page 750
Found 20 reviews on page 751
Found 20 reviews on page 752
Found 20 reviews on page 753
Found 20 reviews on page 754
Found 20 reviews on page 755
Found 20 reviews on page 756
Found 20 reviews on page 757
Found 20 reviews on page 758
Found 20 reviews on page 759
Found 20 reviews on page 760
Reached end page 760

Scraping summary:
- Pages scraped: 20
- Page range: 741 to 760
- Raw reviews: 400
- Duplicates removed: 0
- Final unique reviews: 400
Saved batch #38 with 400 reviews to firstport_reviews_batches/firstport_reviews_batch38_p741-p760_20250427_064739.csv
Updated cumulative results with 15200 total reviews

Pausing between batches (5 seconds)...

==================================================
PROCESSING BATCH #39: Pages 761-780
==================================================
Scraping pages 761 to 780

Scraping pages: 0page [00:00, ?page/s]

Found 20 reviews on page 761
Found 20 reviews on page 762
Found 20 reviews on page 763
Found 20 reviews on page 764
Found 20 reviews on page 765
Found 20 reviews on page 766
Found 20 reviews on page 767
Found 20 reviews on page 768
Found 20 reviews on page 769
Found 20 reviews on page 770
Found 20 reviews on page 771
Found 20 reviews on page 772
Found 20 reviews on page 773
Found 20 reviews on page 774
Found 20 reviews on page 775
Found 20 reviews on page 776
Found 20 reviews on page 777
Found 20 reviews on page 778
Found 20 reviews on page 779
Found 20 reviews on page 780
Reached end page 780

Scraping summary:
- Pages scraped: 20
- Page range: 761 to 780
- Raw reviews: 400
- Duplicates removed: 0
- Final unique reviews: 400
Saved batch #39 with 400 reviews to firstport_reviews_batches/firstport_reviews_batch39_p761-p780_20250427_064739.csv
Updated cumulative results with 15600 total reviews

Pausing between batches (5 seconds)...

==================================================
PROCESSING BATCH #40: Pages 781-800
==================================================
Scraping pages 781 to 800

Scraping pages: 0page [00:00, ?page/s]

Found 20 reviews on page 781
Found 20 reviews on page 782
Found 20 reviews on page 783
Found 20 reviews on page 784
Found 20 reviews on page 785
Found 20 reviews on page 786
Found 20 reviews on page 787
Found 20 reviews on page 788
Found 20 reviews on page 789
Found 20 reviews on page 790
Found 20 reviews on page 791
Found 20 reviews on page 792
Found 20 reviews on page 793
Found 20 reviews on page 794
Found 20 reviews on page 795
Found 20 reviews on page 796
Found 20 reviews on page 797
Found 20 reviews on page 798
Found 20 reviews on page 799
Found 20 reviews on page 800
Reached end page 800

Scraping summary:
- Pages scraped: 20
- Page range: 781 to 800
- Raw reviews: 400
- Duplicates removed: 0
- Final unique reviews: 400
Saved batch #40 with 400 reviews to firstport_reviews_batches/firstport_reviews_batch40_p781-p800_20250427_064739.csv
Updated cumulative results with 16000 total reviews

Pausing between batches (5 seconds)...

==================================================
PROCESSING BATCH #41: Pages 801-807
==================================================
Scraping pages 801 to 807

Scraping pages: 0page [00:00, ?page/s]

Found 20 reviews on page 801
Found 20 reviews on page 802
Found 20 reviews on page 803
Found 20 reviews on page 804
Found 20 reviews on page 805
Found 20 reviews on page 806
Found 8 reviews on page 807
Reached end page 807

Scraping summary:
- Pages scraped: 7
- Page range: 801 to 807
- Raw reviews: 128
- Duplicates removed: 0
- Final unique reviews: 128
Saved batch #41 with 128 reviews to firstport_reviews_batches/firstport_reviews_batch41_p801-p807_20250427_064739.csv
Updated cumulative results with 16128 total reviews
Reached specified end page (807)

In [ ]:
# Display summary
print(f"\nFINAL RESULTS:")
print(f"Total reviews collected: {len(df)}")
if len(df) > 0:
    print("\nSample reviews:")
    display(df.head())

    # Number of reviews by rating
    print("\nDistribution by rating:")
    rating_counts = df['Rating'].value_counts().sort_index()
    display(rating_counts)

    # Save complete dataset to CSV
    filename = f"firstport_reviews_complete.csv"
    df.to_csv(filename, index=False)
    print(f"Saved all {len(df):,} reviews to {filename}")
else:
    print("No reviews collected, CSV not created.")

FINAL RESULTS:
Total reviews collected: 16000

Sample reviews:

,Page,Date,Author,Body,Heading,Rating,Location
0,1,2025-04-25,Douglas Armitt,Always gives 100%. Nothing is to much trouble ...,Always gives 100%,5,GB
1,1,2025-04-24,Catchy,Having moved into Chestnut Court 18 months ago...,Excellent site management.,5,GB
2,1,2025-04-24,Beth Dee,They have a bullying approach and do not liste...,They have a bullying approach and do…,1,GB
3,1,2025-04-24,stuart hurst,Donna Saunders has been a great help and is ve...,Donna Saunders,5,GB
4,1,2025-04-24,Stuart Gaylor,Been asking for statements for the RMC account...,Does anyone at FP care?,1,GB

Distribution by rating:

Rating
0       2
1    6580
2     206
3     162
4     662
5    8388
Name: count, dtype: int64

Saved all 16,000 reviews to firstport_reviews_complete.csv